---
title: "Analyzing data on the level of cognitive processes - ESCoP 2025"
author: "Gidon T. Frischkorn, Ruhi Bhanap, and Isabel Courage"
output:
  pdf_document: default
  html_document: default
---

# Exercise 1: Central Limit Theorem

The central limit theorem states that the sum or average of random samples from any probability distribution with a mean and standard deviation smaller then infinity will approximate a normal distribution, with a sufficient number of samples. This exercise should help you getting an intuition what a "sufficient number" of samples is and what this implies for the assumption of the normal distribution in experimental settings.

Your task is to:

1. Choose any - ideally asymmetric or totally random (e.g. using the `sample` function) - probability distribution.
2. Compute the average of 2, 5, 10, and 20 samples from the distribution for 200 times. 
3. Plot these averages in a histogram and try overlaying the density of the normal distribution with the mean and standard deviation of the plotted values
