---
title: "Exercise 6: Full Drift Diffusion Model"
output: html_document
---

In this exercise, we will have a look at estimating the parameters from the diffusion decision model using the hierarchical Bayesian implementation of the full drift diffusion model. 

1. drift rate = the rate of evidence accumulation
2. boundary seperation = the seperation of decision thresholds
3. non-decision time = the time for non-decisional processes.
4. starting point = the initial bias toward one response alternative over the other.

Your task is to load one of the data sets we prepared for this exercise, either `exercise5_visualsearchtask.txt` or `exc5_ColorJudgement.txt`.

The Color Judgement data set contains data of 50 participants that completed a Color Judgement task. In this task participants saw an array of blue and red dots and should decide if the array contained more blue or red dots. There were two difficulty levels, the easy level in which 60% of the dots were either blue or red, and the difficult level in which 52% of the dots were either blue or red.

The Visual Search data set contains data for 33 participants that completed the Visual Search task. In this task, participants were presented a color cue, a positive (the target color), a negative (the non target color) or neutral (not part of the visual search display). Participants had to look for a "C" that either looked upwards or downwards and report it´s direction with the arrow key. 

Your task is:

1. to specify the full `ddm` model 
2. specify a model formula predicting which parameters you assume to vary as a function of the difficulty level (color judgement data set) / the template type (visual search data set)
3. estimate the model using the `bmm` function and interpret the results with respect to the experimental effects on the model parameters
4. estimate both the "three parameter version" and the "four parameter version" to compare it to the results of `ezdm`
 
