---
title: "Analyzing data on the level of cognitive processes - ESCoP 2025"
author: "Gidon T. Frischkorn, Ruhi Bhanap, and Isabel Courage"
output:
  html_document: default
  pdf_document: default
---

# Exercise 5 - EZ-Diffusion Model

In this exercise, we will have a look at estimating the parameters from the diffusion decision model using the hierarchical Bayesian implementation of the ez-Diffusion Model. This implementation allows for a fast parameter estimation while still providing acceptable recovery of three parameters of interest:

1. drift rate = the rate of evidence accumulation
2. boundary separation = the separation of decision thresholds
3. non-decision time = the time for non-decisional processes.

Your task is to load one of the data sets we prepared for this exercise, either `excercise5_visual_search_task.txt` or `excercise5_color_judgement_task.txt`.

The *Color Judgement* data set contains data of 50 participants that completed a color judgement task. In this task participants saw an array of blue and red dots and should decide if the array contained more blue or red dots. There were two difficulty levels, the easy level in which 60% of the dots were either blue or red, and the difficult level in which 52% of the dots were either blue or red.

The *Visual Search* data set contains data for 33 participants that completed the visual search task. In this task, participants were presented a color cue, a positive (the target color), a negative (the non target color) or neutral (not part of the visual search display). Participants had to look for a "C" that either looked upwards or downwards and report it´s direction with the arrow key.

Your task is:

1. Aggregate the data, so that we can estimate the `ezdm`. 
2. Specify the `ezdm` model object matching the aggregated data of the task.
3. Specify a model formula predicting which parameters you assume to vary as a function of the experimental manipulations (i.e. difficulty level or cue type).
4. Estimate the model using the `bmm` function and interpret the results with respect to the experimental effects on the model parameters. Test whether these effects are substantial.
