---
title: "Exercise 6: Full Diffusion Decision Model"
output: html_document
---

In this exercise, we will have a look at estimating the parameters from the diffusion decision model using the hierarchical Bayesian implementation of the full Diffusion Decision Model. 

Your task is to load one of the data sets we prepared for this exercise, either `exc4_VisualSearch.txt` or `exc5_ColorJudgement.txt`.

The Color Judgement data set contains data of 50 participants that completed a Color Judgement task. In this task participants saw an array of blue and red dots and should decide if the array contained more blue or red dots. There were two difficulty levels, the easy level in which 60% of the dots were either blue or red, and the difficult level in which 52% of the dots were either blue or red.

In this exercise, we implement the four parameter `ddm` and test if participants were biased in responding with one of the two response options (i.e. blue or red). For this we have to specify a `ddm` with the actual responses - that is blue or red - as the response boundaries. Thus, we will recode the `correct_response` variable into a numeric `response` variable, and then estimate the `drift` separetly for the target containing more blue or red dots.

Your task is:

1. preprare the data to include a `response` numeric response variable coding blue as `0` and red as `1`
2. specify the `ddm` model object, with the `rt` in seconds and the newly coded `response` variable as the required variables
3. specify the `bmmformula` with assuming different `drift` dependent on the target (i.e. are there more red or blue dots) and think about which other parameters could reasonably vary by the experimental conditions (e.g. the difficulty of the task)
4. estimate the model using the `bmm` function by passing the `ddm` model object and the `bmmformula`. Check if the model starts sampling then load the saved results file: ` ` (Model estimation for the full `ddm` can run for quite some time) 
5. interpret the results of the saved model object with respect to the experimental effects on the model parameters